language: python

python:
    - "3.6"
    - "3.7"
    - "3.8"

env:
  global:
    - LNBITS_BACKEND_WALLET_CLASS=LNPayWallet
    - LNBITS_FORCE_HTTPS=0
    - LNPAY_API_ENDPOINT=https://lnpay.co/v1/
    - LNPAY_API_KEY=sak_gG5pSFZhFgOLHm26a8hcWvXKt98yd
    - LNPAY_ADMIN_KEY=waka_HqWfOoNE0TPqmQHSYErbF4n9
    - LNPAY_INVOICE_KEY=waki_ZqFEbhrTyopuPlOZButZUw
    - LNPAY_READ_KEY=wakr_6IyTaNrvSeu3jbojSWt4ou6h

install:
    - pip install -r requirements.txt
    - pip install pytest pytest-cov codecov

script:
    - pytest --cov=lnbits

after_success:
    - codecov
